### ISSUE TITLE
Build the Official Documentation of Hacktoberfest Ekiti

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/HacktoberfestEkiti-Docs#1]
Hello there

Please we need someone to build the documentation for Hacktoberfest Ekiti

You should use Docs Site Generators: Docusaurus

You can also read more about Doc as Code here: https://devm.io/programming/docs-as-code-174941

**Comment by AbhishekRP2002** [comment]
Can you assign it to me?I would liketo work on this

**Comment by OSCA-Ado-Ekiti** [comment]
sure, you understand the issue right?

**Comment by devchaos0** [comment]
Can you assign this to me
